sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - main # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 3afbd9f92009f7bcbfc8cd3cb92871c4da2f036d
  keep-history: true
  on:
    branch: gh-pages
  local-dir: public